package com.example.mapper;

import com.example.pojo.GoodsSubcategory;
import java.util.List;

public interface GoodsSubCategoryMapper {

    List<GoodsSubcategory> querySubCategory(Integer gCid);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_goods_subcategory
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_goods_subcategory
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    int insert(GoodsSubcategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_goods_subcategory
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    GoodsSubcategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_goods_subcategory
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    List<GoodsSubcategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_goods_subcategory
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    int updateByPrimaryKey(GoodsSubcategory row);
}