package com.example.mapper;

import com.example.pojo.ShopCart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShopCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_shop_cart
     *
     * @mbg.generated Mon Nov 28 17:57:33 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_shop_cart
     *
     * @mbg.generated Mon Nov 28 17:57:33 CST 2022
     */
    int insert(ShopCart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_shop_cart
     *
     * @mbg.generated Mon Nov 28 17:57:33 CST 2022
     */
    List<ShopCart> selectByPrimaryKey(@Param("uid") Integer id,@Param("isDel") Integer isDel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_shop_cart
     *
     * @mbg.generated Mon Nov 28 17:57:33 CST 2022
     */
    ShopCart queryBygId(@Param("gId") int gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_shop_cart
     *
     * @mbg.generated Mon Nov 28 17:57:33 CST 2022
     */
    int updateByPrimaryKey(@Param("count")Integer count,@Param("gId") Integer gId,@Param("isDel") Integer isDel);
}