package com.example.mapper;

import com.example.pojo.SsComment;
import java.util.List;

public interface SsCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_comment
     *
     * @mbg.generated Mon Nov 28 00:04:05 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_comment
     *
     * @mbg.generated Mon Nov 28 00:04:05 CST 2022
     */
    int insert(SsComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_comment
     *
     * @mbg.generated Mon Nov 28 00:04:05 CST 2022
     */
    SsComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_comment
     *
     * @mbg.generated Mon Nov 28 00:04:05 CST 2022
     */
    List<SsComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_comment
     *
     * @mbg.generated Mon Nov 28 00:04:05 CST 2022
     */
    int updateByPrimaryKey(SsComment row);
}