package com.example.mapper;

import com.example.pojo.SsUser;
import java.util.List;

public interface SsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_user
     *
     * @mbg.generated Tue Nov 29 22:06:28 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_user
     *
     * @mbg.generated Tue Nov 29 22:06:28 CST 2022
     */
    int insert(SsUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_user
     *
     * @mbg.generated Tue Nov 29 22:06:28 CST 2022
     */
    SsUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_user
     *
     * @mbg.generated Tue Nov 29 22:06:28 CST 2022
     */
    List<SsUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_user
     *
     * @mbg.generated Tue Nov 29 22:06:28 CST 2022
     */
    int updateByPrimaryKey(SsUser row);
}