package com.example.pojo;

public class GoodsSubcategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_goods_subcategory.scid
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    private Integer scid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_goods_subcategory.cid
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_goods_subcategory.sc_name
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    private String scName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_goods_subcategory.scid
     *
     * @return the value of ss_goods_subcategory.scid
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public Integer getScid() {
        return scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_goods_subcategory.scid
     *
     * @param scid the value for ss_goods_subcategory.scid
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public void setScid(Integer scid) {
        this.scid = scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_goods_subcategory.cid
     *
     * @return the value of ss_goods_subcategory.cid
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_goods_subcategory.cid
     *
     * @param cid the value for ss_goods_subcategory.cid
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_goods_subcategory.sc_name
     *
     * @return the value of ss_goods_subcategory.sc_name
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public String getScName() {
        return scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_goods_subcategory.sc_name
     *
     * @param scName the value for ss_goods_subcategory.sc_name
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public void setScName(String scName) {
        this.scName = scName;
    }
}