package com.example.pojo;

public class GoodsCover {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_goods_cover.id
     *
     * @mbg.generated Sun Nov 27 22:57:31 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_goods_cover.g_id
     *
     * @mbg.generated Sun Nov 27 22:57:31 CST 2022
     */
    private Integer gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_goods_cover.path
     *
     * @mbg.generated Sun Nov 27 22:57:31 CST 2022
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_goods_cover.id
     *
     * @return the value of ss_goods_cover.id
     *
     * @mbg.generated Sun Nov 27 22:57:31 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_goods_cover.id
     *
     * @param id the value for ss_goods_cover.id
     *
     * @mbg.generated Sun Nov 27 22:57:31 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_goods_cover.g_id
     *
     * @return the value of ss_goods_cover.g_id
     *
     * @mbg.generated Sun Nov 27 22:57:31 CST 2022
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_goods_cover.g_id
     *
     * @param gId the value for ss_goods_cover.g_id
     *
     * @mbg.generated Sun Nov 27 22:57:31 CST 2022
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_goods_cover.path
     *
     * @return the value of ss_goods_cover.path
     *
     * @mbg.generated Sun Nov 27 22:57:31 CST 2022
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_goods_cover.path
     *
     * @param path the value for ss_goods_cover.path
     *
     * @mbg.generated Sun Nov 27 22:57:31 CST 2022
     */
    public void setPath(String path) {
        this.path = path;
    }
}