package com.example.pojo;

public class GoodsSubcategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_goods_subcategory.id
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_goods_subcategory.gCid
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    private Integer gCid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_goods_subcategory.name
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_goods_subcategory.id
     *
     * @return the value of ss_goods_subcategory.id
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_goods_subcategory.id
     *
     * @param id the value for ss_goods_subcategory.id
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_goods_subcategory.gCid
     *
     * @return the value of ss_goods_subcategory.gCid
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public Integer getgCid() {
        return gCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_goods_subcategory.gCid
     *
     * @param gCid the value for ss_goods_subcategory.gCid
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public void setgCid(Integer gCid) {
        this.gCid = gCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_goods_subcategory.name
     *
     * @return the value of ss_goods_subcategory.name
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_goods_subcategory.name
     *
     * @param name the value for ss_goods_subcategory.name
     *
     * @mbg.generated Mon Nov 21 03:53:46 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}