package com.example.pojo;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_user.id
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_user.nickname
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_user.username
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_user.password
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_user.avatar
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_user.gender
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_user.is_del
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_user.create_by
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_user.create_time
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_user.update_by
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_user.update_time
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_user.id
     *
     * @return the value of ss_user.id
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_user.id
     *
     * @param id the value for ss_user.id
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_user.nickname
     *
     * @return the value of ss_user.nickname
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_user.nickname
     *
     * @param nickname the value for ss_user.nickname
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_user.username
     *
     * @return the value of ss_user.username
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_user.username
     *
     * @param username the value for ss_user.username
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_user.password
     *
     * @return the value of ss_user.password
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_user.password
     *
     * @param password the value for ss_user.password
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_user.avatar
     *
     * @return the value of ss_user.avatar
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_user.avatar
     *
     * @param avatar the value for ss_user.avatar
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_user.gender
     *
     * @return the value of ss_user.gender
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_user.gender
     *
     * @param gender the value for ss_user.gender
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_user.is_del
     *
     * @return the value of ss_user.is_del
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_user.is_del
     *
     * @param isDel the value for ss_user.is_del
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_user.create_by
     *
     * @return the value of ss_user.create_by
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_user.create_by
     *
     * @param createBy the value for ss_user.create_by
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_user.create_time
     *
     * @return the value of ss_user.create_time
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_user.create_time
     *
     * @param createTime the value for ss_user.create_time
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_user.update_by
     *
     * @return the value of ss_user.update_by
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_user.update_by
     *
     * @param updateBy the value for ss_user.update_by
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_user.update_time
     *
     * @return the value of ss_user.update_time
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_user.update_time
     *
     * @param updateTime the value for ss_user.update_time
     *
     * @mbg.generated Sun Nov 20 00:19:19 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}